#开发环境
server:
  port: 8083

spring:
  datasource:
    dynamic:
      #连接池配置
      druid:
        initial-size: 5
        min-idle: 5
        max-active: 20
        max-wait: 6000
        time-between-eviction-runs-millis: 60000
        min-evictable-idle-time-millis: 300000
        validation-query: SELECT 1
        test-while-idle: true
        test-on-borrow: false
        test-on-return: false
        max-pool-prepared-statement-per-connection-size: 20
        pool-prepared-statements: true
      primary: wincare2 #设置默认的数据源或者数据源组,默认值即为master
      strict: false #设置严格模式,默认false不启动. 启动后在未匹配到指定数据源时候回抛出异常,不启动会使用默认数据源.
      datasource:
        wincare2:
          url: jdbc:sqlserver://10.167.23.70:1433;DatabaseName=WINCARE2
          username: sa
          password: Zpm672168300
          driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
        wincare3:
          url: jdbc:sqlserver://10.167.23.70:1433;DatabaseName=WINCARE3
          username: sa
          password: Zpm672168300
          driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
        wincare4:
          url: jdbc:sqlserver://10.167.23.70:1433;DatabaseName=WINCARE4
          username: sa
          password: Zpm672168300
          driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
        officeBrain2:
          url: jdbc:sqlserver://10.167.23.70:1433;DatabaseName=OfficeBrain2
          username: sa
          password: Zpm672168300
          driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
        officeBrain3:
          url: jdbc:sqlserver://10.167.23.70:1433;DatabaseName=OfficeBrain3
          username: sa
          password: Zpm672168300
          driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
        officeBrain4:
          url: jdbc:sqlserver://10.167.23.70:1433;DatabaseName=OfficeBrain4
          username: sa
          password: Zpm672168300
          driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver





mybatis:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  mapper-locations: classpath*:com/fujitsu/wow/mapper/xml/**/*.xml

logging:
  config: classpath:logback-spring.xml



